### ISSUE TITLE
 error while reopening the container

### ISSUE THREAD

**Issue by ninodamico** [cheshire-cat-ai/local-cat#21]
good evening
 I am working with local cat, and I have inserted my db into compose to be able to work with the sql plugin. Sometimes the error of which I attach the screen appears after closing and restarting the container. As a result the cut doesn't work! what could be the problem?! Am I doing something wrong!?

thanks for your attention
![image (1)](https://github.com/user-attachments/assets/031c8464-4b2c-43a6-8bf7-0a2355d14c1a)

**Comment by pieroit** [comment]
The LLM service is giving non string replies, or network errors

Should not be a Cat issue.
Please verify your LLM vendor/setup and reopen this issue only if it os actually on the Cat
