### ISSUE TITLE
plugin AiChatSql inaccurate

### ISSUE THREAD

**Issue by ninodamico** [cheshire-cat-ai/local-cat#22]
I downloaded the AiChatSql plugin, which allows you to formulate queries to the connected database simply by asking the cat in natural language what information we want. But the cat appears very unstable, it doesn't always respond, the tool isn't always able to be invoked, and when it does it often makes mistakes. It would be necessary to solve these problems. Could it be a solution to modify the plugin tool by inserting the database schema directly into the code?!

**Comment by pieroit** [comment]
Hi @ninodamico, contact the plugin developer on the plugin repo (in the admin you can find the link).

Closing here as this is the repo for a local cat installation
