### ISSUE TITLE
Docker on OsX does not support GPUs acceleration

### ISSUE THREAD

**Issue by lecciovich** [cheshire-cat-ai/local-cat#5]
As stated in [Ollama website](https://ollama.ai/blog/ollama-is-now-available-as-an-official-docker-image?ref=upstract.com), to run containers, Docker uses a VM on Mac.
It uses Apples own hypervisor, which doesn't provide GPU access.
So, Ollama on Docker on MacOS isn't not GPU accelerated.
The menu bar app version of Ollama,anyway, is GPU accelerated on Apple Silicon.

Are there other ways to accelerate an Ollama containers on OsX?
If answer is no, wait next Apple announcement on their hypervisor at WWDC next year.

**Comment by valentimarco** [comment]
We can resolve this issue by setting the default url of ollama to `http://0.0.0.0:11434`

**Comment by valentimarco** [comment]
Close with #19 merged
