### ISSUE TITLE
looks like some plugins stop ollama_cat from running.

### ISSUE THREAD

**Issue by jamenlang** [cheshire-cat-ai/local-cat#8]
this could be a coincidence, but I tried to install the plugin for dietician and got an error No module named 'langchain.embeddings.fastembed'

I removed the plugin from the local-cat/cat/plugins directory, 

I still get the same error when I use docker-compose up

![image](https://github.com/cheshire-cat-ai/local-cat/assets/6394127/66759930-9694-4a55-a22e-852878538b0e)

**Comment by pieroit** [comment]
Yep, dietician plugin breaks the new versions of the cat by requiring an old langchain version
Delete the plugin and rebuild, we'll notifiy plugin's author

**Comment by valentimarco** [comment]
the dietician plugin was updated
